site_name: Android SDK
repo_name: mobile-sdk-android
repo_url: https://github.com/Jumio/mobile-sdk-android

copyright: Copyright &copy; 2023 Jumio

theme: 
  name: material
  logo: images/logos/jumio-white-logo-nav.svg
  favicon: images/logos/jumio-favicon.png
  palette:
    primary: indigo
    accent: teal

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.side
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate

docs_dir: docs

nav:
  - Home: index.md
  - Integration: integration_guide.md
  - SDK Changes:
    - Release Notes: changelog.md
    - Transition Guide: transition_guide.md
  - Resources:
    - FAQ: integration_faq.md
    - Known Issues: known_issues.md
    - Glossary: integration_glossary.md
  - Support Policy: maintenance_policy.md
  - Sample App: https://github.com/Jumio/mobile-sdk-android/tree/master/sample/JumioMobileSample

extra:
  author: Bernadette Th
  version: 1.0.0
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Jumio
    

dev_addr: 127.0.0.1:8000
